version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file: .env

  api:
    build: .
    command: uvicorn app.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8004:8000"
    env_file: .env

volumes:
  postgres_data:
